export const SELECTED_COUNTRY = "SELECTED_COUNTRY";
export const SET_COUNTRY_INFO = "SET_COUNTRY_INFO";
export const FETCH_COUNTRIES_REQUEST = "FETCH_COUNTRIES_REQUEST";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILURE = "FETCH_COUNTRIES_FAILURE";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
